server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbapp?user=poc&password=poc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers:
      - LAPTOP-AGNDBVK8.localdomain:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers:
      - LAPTOP-AGNDBVK8.localdomain:9092
      group-id: individu
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "com.poc"  
debitur:
  product-out-to-debitur-topic-name: product-out-to-debitur
  debitur-out-to-kredit-topic-name: debitur-out-to-kredit
  debitur-out-to-feeder-topic-name: debitur-out-to-feeder
  
  