server:
  port: 8085
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbapp?user=poc&password=poc
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
     producer:
      bootstrap-servers:
      - LAPTOP-AGNDBVK8.localdomain:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
     consumer:
      bootstrap-servers:
      - LAPTOP-AGNDBVK8.localdomain:9092
      group-id: kredit
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "com.poc"
kredit:
  kredit-out-to-transaction-topic-name: kredit-out-to-transaction
  kredit-out-to-inquiry-topic-name: kredit-out-to-inquiry
  debitur-out-to-kredit-topic-name: debitur-out-to-kredit
  feeder-out-to-kredit-topic-name: feeder-out-to-kredit
  product-in-from-kredit-topic-name: product-in-from-kredit
