name: debitur

on:
  push:
    branches: [ main ]
    paths:
      - event-driven/debitur/**
      - .github/workflows/debitur.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: debitur
      jar_name: debitur-0.0.1-SNAPSHOT.jar
#test
