on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
        
env:
  USERNAME: ret97
  PASSWORD: mahendra@

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build application
        run: cd event-driven && mvn -DskipTests=true clean package --projects :${{ inputs.service }} --also-make --batch-mode

      - name: Check File
        run: cd event-driven/${{ inputs.service }}/target && ls -la
        
      - name: Login to Docker Hub
        #run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        uses: docker/login-action@v2
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
            
      - name: Build the Docker image
        run: docker build . --build-arg JAR_FILE=event-driven/${{ inputs.service }}/target/${{ inputs.jar_name }} -t ret97/fibrcorp-${{ inputs.service }}:test

      - name: Docker Push
        run: docker push ret97/fibrcorp-${{ inputs.service }}:test
        
      # Build and push docker image
      # docker build . --build-arg JAR_FILE=services/${{ inputs.service }}/target/app.jar -t <tag>
